#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x picom > /dev/null || picom --animations --animation-for-open-window fly-in --experimental-backends &
pgrep -x picom > /dev/null || picom -b --experimental-backends --config $HOME/.config/picom/picom.conf

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# My Rules
bspc rule -a Firefox-esr desktop='^3'
bspc rule -a Firefox-esr:Places state=floating center=on
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Thunar desktop='^2'
bspc rule -a Xarchiver state=floating
bspc rule -a Pavucontrol state= floating rectangle=748x478+0+0 center=on 
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Nsxiv state=floating

# Pywal
wal -R
. "${HOME}/.cache/wal/colors.sh"
pc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"



# nm-applet
nm-applet &

# Fix Java
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

# Fix Change X shaped default cursor
xsetroot -cursor_name left_ptr &

# Wallpaper
feh --bg-fill $HOME/Imágenes/Wallpapers/Minimalistic/tokyo.png &

# Polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# Polybar
$HOME/.config/polybar/launch.sh &

# Resolution
/home/daniel/.screenlayout/screen.sh &

# Block-Screnn
xss-lock -- betterlockscreen -l dimblur &
